update cicd

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -9,111 +9,96 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # 1. Checkout
-    - name: Checkout code
-      uses: actions/checkout@v3
+      # 1. Checkout
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    # 2. Setup Node
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-      node-version: "18"
+      # 2. Setup Node
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "18"
 
-  # 3. Check structure
-    - name: Check project structure
-      run: |
-        set -e
-        test -d backend || (echo "backend missing" && exit 1)
-        test -d frontend || (echo "frontend missing" && exit 1)
+      # 3. Check structure
+      - name: Check project structure
+        run: |
+          set -e
+          test -d backend || (echo "backend missing" && exit 1)
+          test -d frontend || (echo "frontend missing" && exit 1)
 
-  # 4. Validate files
-    - name: Validate required files
-      run: |
-        set -e
-        test -f backend/package.json || (echo "backend/package.json missing" && exit 1)
-        test -f nginx/nginx.conf || (echo "nginx.conf missing" && exit 1)
+      # 4. Validate files
+      - name: Validate required files
+        run: |
+          set -e
+          test -f backend/package.json || (echo "backend/package.json missing" && exit 1)
+          test -f nginx/nginx.conf || (echo "nginx.conf missing" && exit 1)
 
-  # 5. Install backend deps
-    - name: Install backend
-      run: |
-        cd backend
-        npm ci
+      # 5. Install backend deps
+      - name: Install backend
+        run: |
+          cd backend
+          npm ci
 
-  # 6. Lint + format
-    - name: Code quality check
-      run: |
-        cd backend
-        npm run lint
-        npm run format:check
+      # 6. Lint + format
+      - name: Code quality check
+        run: |
+          cd backend
+          npm run lint
+          npm run format:check
 
-  # 7. Build backend Docker image 
-    - name: Build backend image
-      run: |
-        docker build -t test-backend ./backend
+      # 7. Build backend Docker image
+      - name: Build backend image
+        run: docker build -t test-backend ./backend
 
-    # 8. Build nginx Docker image 
-    - name: Build nginx image
-      run: |
-        docker build -t test-nginx -f nginx/Dockerfile .
-
+      # 8. Build nginx Docker image
+      - name: Build nginx image
+        run: docker build -t test-nginx -f nginx/Dockerfile .
 
   cd:
-    needs: ci 
+    needs: ci
     runs-on: ubuntu-latest
 
     steps:
-    # 1. Checkout
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    # 2. Config AWS
-    - name: Configure AWS
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AWS_REGION }}
+      - name: Configure AWS
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
 
-    # 3. Login ECR
-    - name: Login to ECR
-      uses: aws-actions/amazon-ecr-login@v2
+      - name: Login to ECR
+        uses: aws-actions/amazon-ecr-login@v2
 
-    # 4. Build & Push backend
-    - name: Build backend
-      run: |
-        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todo-backend
+      - name: Build & Push backend
+        run: |
+          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todo-backend
+          docker build -t $IMAGE:${{ github.sha }} ./backend
+          docker push $IMAGE:${{ github.sha }}
 
-        docker build -t $IMAGE:${{ github.sha }} ./backend
-        docker push $IMAGE:${{ github.sha }}
+      - name: Build & Push nginx
+        run: |
+          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todo-nginx
+          docker build -t $IMAGE:${{ github.sha }} -f nginx/Dockerfile .
+          docker push $IMAGE:${{ github.sha }}
 
-    # 5. Build & Push nginx
-    - name: Build nginx
-      run: |
-        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todo-nginx
+      - name: Deploy EC2
+        uses: appleboy/ssh-action@v1.0.0
+        with:
+          host: ${{ secrets.SERVER_IP2 }}
+          username: ec2-user
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+            cd /home/ec2-user/todoapp
 
-        docker build -t $IMAGE:${{ github.sha }} -f nginx/Dockerfile .
-        docker push $IMAGE:${{ github.sha }}
+            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
+              | docker login --username AWS --password-stdin \
+              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
 
-    # 6. Deploy EC2
-    - name: Deploy EC2
-      uses: appleboy/ssh-action@v1.0.0
-      with:
-        host: ${{ secrets.SERVER_IP2 }}
-        username: ec2-user
-        key: ${{ secrets.SSH_KEY }}
-        script: |
-          cd /home/ec2-user/todoapp
+            sed -i '/^TAG=/d' .env
+            echo "TAG=${{ github.sha }}" >> .env
 
-          # login ECR
-          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
-            | docker login --username AWS --password-stdin \
-            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
-
-          # update TAG
-          sed -i '/^TAG=/d' .env
-          echo "TAG=${{ github.sha }}" >> .env
-
-          # deploy
-          docker compose pull
-          docker compose down
-          docker compose up -d
+            docker compose pull
+            docker compose up -d
